//@base_url = http://localhost:3000/api

### Create a new Todo
//POST {{base_url}}/item
POST http://localhost:3000/api/auth/login
Content-Type: application/json

{
    "username": "MoyinDoskey26$",
    "password": "TodoApp1234"
}
